#!/bin/bash
#SBATCH --job-name=pp_unet_4
#SBATCH --output=logs/postproc_unet_exp4_%j.log
#SBATCH --error=logs/postproc_unet_exp4_%j.log
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --time=12:00:00
#SBATCH --mem=64G
#SBATCH --account=CLIMAT-UM6P-ST-IWRI-7KSIFKVWKUY-DEFAULT-CPU

source ~/.bashrc
conda activate clean_env_Pytorch

export PYTHONUNBUFFERED=1

echo "======================================"
echo "Job ID: $SLURM_JOB_ID"
echo "Post-processing UNet Experiment: 4"
echo "======================================"

echo "Waiting for all 12 output files to be generated by training jobs..."
files=(
"/srv/data/mohammad.elaabaribao/work/papers/downscaling/main/results/unet_exp4_coordconv_mse_bs64_lr1e-3/region_lat_21.0_37.0_lon_-18.0_0.0/train_1979_01_01_2005_12_31/test_2006_01_01_2020_12_31/gridbox_0.001_mse_150ep_lr_sched_wd_gc_dropout_gn/output_data/unet_coordconv_predictions_era5_to_mswep.nc"
"/srv/data/mohammad.elaabaribao/work/papers/downscaling/main/results/unet_exp4_coordconv_mse_bs64_lr1e-4/region_lat_21.0_37.0_lon_-18.0_0.0/train_1979_01_01_2005_12_31/test_2006_01_01_2020_12_31/gridbox_0.0001_mse_150ep_lr_sched_wd_gc_dropout_gn/output_data/unet_coordconv_predictions_era5_to_mswep.nc"
"/srv/data/mohammad.elaabaribao/work/papers/downscaling/main/results/unet_exp4_coordconv_mse_bs64_lr1e-5/region_lat_21.0_37.0_lon_-18.0_0.0/train_1979_01_01_2005_12_31/test_2006_01_01_2020_12_31/gridbox_1e-05_mse_150ep_lr_sched_wd_gc_dropout_gn/output_data/unet_coordconv_predictions_era5_to_mswep.nc"
"/srv/data/mohammad.elaabaribao/work/papers/downscaling/main/results/unet_exp4_coordconv_mse_bs128_lr1e-3/region_lat_21.0_37.0_lon_-18.0_0.0/train_1979_01_01_2005_12_31/test_2006_01_01_2020_12_31/gridbox_0.001_mse_150ep_lr_sched_wd_gc_dropout_gn/output_data/unet_coordconv_predictions_era5_to_mswep.nc"
"/srv/data/mohammad.elaabaribao/work/papers/downscaling/main/results/unet_exp4_coordconv_mse_bs128_lr1e-4/region_lat_21.0_37.0_lon_-18.0_0.0/train_1979_01_01_2005_12_31/test_2006_01_01_2020_12_31/gridbox_0.0001_mse_150ep_lr_sched_wd_gc_dropout_gn/output_data/unet_coordconv_predictions_era5_to_mswep.nc"
"/srv/data/mohammad.elaabaribao/work/papers/downscaling/main/results/unet_exp4_coordconv_mse_bs128_lr1e-5/region_lat_21.0_37.0_lon_-18.0_0.0/train_1979_01_01_2005_12_31/test_2006_01_01_2020_12_31/gridbox_1e-05_mse_150ep_lr_sched_wd_gc_dropout_gn/output_data/unet_coordconv_predictions_era5_to_mswep.nc"
"/srv/data/mohammad.elaabaribao/work/papers/downscaling/main/results/unet_exp4_coordconv_mse_bs512_lr1e-3/region_lat_21.0_37.0_lon_-18.0_0.0/train_1979_01_01_2005_12_31/test_2006_01_01_2020_12_31/gridbox_0.001_mse_150ep_lr_sched_wd_gc_dropout_gn/output_data/unet_coordconv_predictions_era5_to_mswep.nc"
"/srv/data/mohammad.elaabaribao/work/papers/downscaling/main/results/unet_exp4_coordconv_mse_bs512_lr1e-4/region_lat_21.0_37.0_lon_-18.0_0.0/train_1979_01_01_2005_12_31/test_2006_01_01_2020_12_31/gridbox_0.0001_mse_150ep_lr_sched_wd_gc_dropout_gn/output_data/unet_coordconv_predictions_era5_to_mswep.nc"
"/srv/data/mohammad.elaabaribao/work/papers/downscaling/main/results/unet_exp4_coordconv_mse_bs512_lr1e-5/region_lat_21.0_37.0_lon_-18.0_0.0/train_1979_01_01_2005_12_31/test_2006_01_01_2020_12_31/gridbox_1e-05_mse_150ep_lr_sched_wd_gc_dropout_gn/output_data/unet_coordconv_predictions_era5_to_mswep.nc"
"/srv/data/mohammad.elaabaribao/work/papers/downscaling/main/results/unet_exp4_coordconv_mse_bs1024_lr1e-3/region_lat_21.0_37.0_lon_-18.0_0.0/train_1979_01_01_2005_12_31/test_2006_01_01_2020_12_31/gridbox_0.001_mse_150ep_lr_sched_wd_gc_dropout_gn/output_data/unet_coordconv_predictions_era5_to_mswep.nc"
"/srv/data/mohammad.elaabaribao/work/papers/downscaling/main/results/unet_exp4_coordconv_mse_bs1024_lr1e-4/region_lat_21.0_37.0_lon_-18.0_0.0/train_1979_01_01_2005_12_31/test_2006_01_01_2020_12_31/gridbox_0.0001_mse_150ep_lr_sched_wd_gc_dropout_gn/output_data/unet_coordconv_predictions_era5_to_mswep.nc"
"/srv/data/mohammad.elaabaribao/work/papers/downscaling/main/results/unet_exp4_coordconv_mse_bs1024_lr1e-5/region_lat_21.0_37.0_lon_-18.0_0.0/train_1979_01_01_2005_12_31/test_2006_01_01_2020_12_31/gridbox_1e-05_mse_150ep_lr_sched_wd_gc_dropout_gn/output_data/unet_coordconv_predictions_era5_to_mswep.nc"
)

for file in "${files[@]}"; do
    while [ ! -f "$file" ]; do
        echo "Waiting for $file..."
        sleep 600
    done
done

echo "All required .nc files found! Starting post-processing."
python3 -u postproc.py tests/config_unet_exp4.yaml

echo "======================================"
echo "Job completed."
echo "======================================"
