experiment: vits_glm_vs_cnn_lmdz250
parameters:
  start_date: '1979-01-01'
  end_date: '2014-12-31'
  region: allmorr
  regions:
  - allmorr
  mask_land: true
  only_morocco: true
  predictand: pr
  plot_only: false
  impose_robust_limits: true
  show_title_metadata: true
  plot_periods:
  - Annual
  - DJF
  - MAM
  - JJA
  - SON
reference:
  name: mswep
  file_path: /home/mohammad.elaabaribao/lustre/climat-um6p-st-iwri-7ksifkvwkuy/users/mohammad.elaabaribao/data//era5ztquv/1979_2020/all_data/mswep_1979_2020.nc
  variable_name: precipitation
datasets:
- name: unet
  file_path: ../inference/results/1979_2014/cnn_exp3/cnn_lmdz_250_present_true.nc
  variable_name: precipitation
- name: cnn
  file_path: ../inference/results/1979_2014/cnn_exp5/cnn_lmdz_250_present_true.nc
  variable_name: precipitation
- name: glm
  file_path: ../inference/results/1979_2014/glm_precip_l2/glm_lmdz_250_present_true.nc
  variable_name: precipitation
- name: ViT
  file_path: ../inference/results/1979_2014/vit_precip_exp21_best_hybrid/vit_lmdz_250_present_true.nc
  variable_name: precipitation
postproc:
  mean:
    enable: true
    bias: true
    rmse: true
    correlation: true
  extreme:
    enable: true
    cdd: true
    qqplot: false
    r01: false
    r99: false
    r95: true
    r99_freq: false
    r95_freq: true
    rocss: false
custom_limits:
  bias:
    spatial:
    - -2
    - -1.5
    - -1
    - -0.5
    - -0.2
    - 0
    - 0.2
    - 0.5
    - 1
    - 1.5
    - 2
    boxplot:
    - -1
    - 1
    temporal:
    - -1
    - 1
  rmse:
    spatial:
    - 0
    - 0.2
    - 0.4
    - 0.6
    - 0.8
    - 1.0
    - 1.5
    - 2.0
    boxplot:
    - 0
    - 1
    temporal:
    - 0
    - 1
  mean:
    spatial:
    - 0
    - 0.1
    - 0.3
    - 0.5
    - 1
    - 2
    - 3
    - 4
    - 5
    boxplot:
    - 0
    - 6
    temporal:
    - 0
    - 0.1
    - 0.3
    - 0.5
    - 1
    - 2
    - 3
    - 4
    - 5
  cdd:
    spatial:
    - 0
    - 25
    - 50
    - 75
    - 100
    - 125
    - 150
    - 175
    - 200
    - 225
    - 250
    - 275
    - 300
    - 325
    - 350
    - 375
    - 400
    boxplot:
    - 0
    - 400
    temporal:
    - 100
    - 400
  r01:
    spatial:
    - 0
    - 10
    - 20
    - 30
    - 40
    - 50
    - 60
    - 70
    - 80
    boxplot:
    - 0
    - 80
    temporal:
    - 0
    - 80
  r95:
    spatial:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    boxplot:
    - 0
    - 6
    temporal:
    - 0
    - 6
  r99:
    spatial:
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 15
    boxplot:
    - 0
    - 15
    temporal:
    - 0
    - 15
  r95_freq:
    spatial:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    boxplot:
    - 0
    - 5
    temporal:
    - 0
    - 5
  r99_freq:
    spatial:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    boxplot:
    - 0
    - 6
    temporal:
    - 0
    - 6
  qqplot:
    spatial:
    - 0
    - 20
    - 40
    - 60
    - 80
    boxplot:
    - 0
    - 80
    temporal:
    - 0
    - 80
  correlation:
    spatial:
    - -1
    - -0.8
    - -0.6
    - -0.4
    - -0.2
    - 0
    - 0.2
    - 0.4
    - 0.6
    - 0.8
    - 1
    boxplot:
    - -1
    - 1
    temporal:
    - -1
    - 1
  rocss:
    spatial:
    - 0
    - 0.2
    - 0.4
    - 0.6
    - 0.8
    - 1
    boxplot:
    - 0
    - 1
    temporal:
    - 0
    - 1
