experiment: unet_exp1_sweep_postproc
parameters:
  start_date: '2006-01-01'
  end_date: '2020-12-31'
  region: allmorr
  regions:
  - allmorr
  mask_land: true
  only_morocco: true
  predictand: pr
  plot_only: false
  impose_robust_limits: true
  show_title_metadata: true
  plot_periods:
  - Annual
  - DJF
  - MAM
  - JJA
  - SON
reference:
  name: mswep
  file_path: /home/mohammad.elaabaribao/lustre/climat-um6p-st-iwri-7ksifkvwkuy/users/mohammad.elaabaribao/data/era5ztquv/1979_2020/all_data/mswep_1979_2020.nc
  variable_name: precipitation
datasets:
- name: bs64_lr1e-3
  file_path: /srv/data/mohammad.elaabaribao/work/papers/downscaling/main/results/tests/unet/unet_exp1_v2_bg_bs64_lr1e-3/region_lat_21.0_37.0_lon_-18.0_0.0/train_1979_01_01_2005_12_31/test_2006_01_01_2020_12_31/gridbox_0.001_bernoulli_gamma_150ep_lr_sched_wd_gc_dropout_gn/output_data/unet_v2_predictions_era5_to_mswep.nc
  variable_name: precipitation
- name: bs64_lr1e-4
  file_path: /srv/data/mohammad.elaabaribao/work/papers/downscaling/main/results/tests/unet/unet_exp1_v2_bg_bs64_lr1e-4/region_lat_21.0_37.0_lon_-18.0_0.0/train_1979_01_01_2005_12_31/test_2006_01_01_2020_12_31/gridbox_0.0001_bernoulli_gamma_150ep_lr_sched_wd_gc_dropout_gn/output_data/unet_v2_predictions_era5_to_mswep.nc
  variable_name: precipitation
- name: bs64_lr1e-5
  file_path: /srv/data/mohammad.elaabaribao/work/papers/downscaling/main/results/tests/unet/unet_exp1_v2_bg_bs64_lr1e-5/region_lat_21.0_37.0_lon_-18.0_0.0/train_1979_01_01_2005_12_31/test_2006_01_01_2020_12_31/gridbox_1e-05_bernoulli_gamma_150ep_lr_sched_wd_gc_dropout_gn/output_data/unet_v2_predictions_era5_to_mswep.nc
  variable_name: precipitation
- name: bs128_lr1e-3
  file_path: /srv/data/mohammad.elaabaribao/work/papers/downscaling/main/results/tests/unet/unet_exp1_v2_bg_bs128_lr1e-3/region_lat_21.0_37.0_lon_-18.0_0.0/train_1979_01_01_2005_12_31/test_2006_01_01_2020_12_31/gridbox_0.001_bernoulli_gamma_150ep_lr_sched_wd_gc_dropout_gn/output_data/unet_v2_predictions_era5_to_mswep.nc
  variable_name: precipitation
- name: bs128_lr1e-4
  file_path: /srv/data/mohammad.elaabaribao/work/papers/downscaling/main/results/tests/unet/unet_exp1_v2_bg_bs128_lr1e-4/region_lat_21.0_37.0_lon_-18.0_0.0/train_1979_01_01_2005_12_31/test_2006_01_01_2020_12_31/gridbox_0.0001_bernoulli_gamma_150ep_lr_sched_wd_gc_dropout_gn/output_data/unet_v2_predictions_era5_to_mswep.nc
  variable_name: precipitation
- name: bs128_lr1e-5
  file_path: /srv/data/mohammad.elaabaribao/work/papers/downscaling/main/results/tests/unet/unet_exp1_v2_bg_bs128_lr1e-5/region_lat_21.0_37.0_lon_-18.0_0.0/train_1979_01_01_2005_12_31/test_2006_01_01_2020_12_31/gridbox_1e-05_bernoulli_gamma_150ep_lr_sched_wd_gc_dropout_gn/output_data/unet_v2_predictions_era5_to_mswep.nc
  variable_name: precipitation
- name: bs512_lr1e-3
  file_path: /srv/data/mohammad.elaabaribao/work/papers/downscaling/main/results/tests/unet/unet_exp1_v2_bg_bs512_lr1e-3/region_lat_21.0_37.0_lon_-18.0_0.0/train_1979_01_01_2005_12_31/test_2006_01_01_2020_12_31/gridbox_0.001_bernoulli_gamma_150ep_lr_sched_wd_gc_dropout_gn/output_data/unet_v2_predictions_era5_to_mswep.nc
  variable_name: precipitation
- name: bs512_lr1e-4
  file_path: /srv/data/mohammad.elaabaribao/work/papers/downscaling/main/results/tests/unet/unet_exp1_v2_bg_bs512_lr1e-4/region_lat_21.0_37.0_lon_-18.0_0.0/train_1979_01_01_2005_12_31/test_2006_01_01_2020_12_31/gridbox_0.0001_bernoulli_gamma_150ep_lr_sched_wd_gc_dropout_gn/output_data/unet_v2_predictions_era5_to_mswep.nc
  variable_name: precipitation
- name: bs512_lr1e-5
  file_path: /srv/data/mohammad.elaabaribao/work/papers/downscaling/main/results/tests/unet/unet_exp1_v2_bg_bs512_lr1e-5/region_lat_21.0_37.0_lon_-18.0_0.0/train_1979_01_01_2005_12_31/test_2006_01_01_2020_12_31/gridbox_1e-05_bernoulli_gamma_150ep_lr_sched_wd_gc_dropout_gn/output_data/unet_v2_predictions_era5_to_mswep.nc
  variable_name: precipitation
- name: bs1024_lr1e-3
  file_path: /srv/data/mohammad.elaabaribao/work/papers/downscaling/main/results/tests/unet/unet_exp1_v2_bg_bs1024_lr1e-3/region_lat_21.0_37.0_lon_-18.0_0.0/train_1979_01_01_2005_12_31/test_2006_01_01_2020_12_31/gridbox_0.001_bernoulli_gamma_150ep_lr_sched_wd_gc_dropout_gn/output_data/unet_v2_predictions_era5_to_mswep.nc
  variable_name: precipitation
- name: bs1024_lr1e-4
  file_path: /srv/data/mohammad.elaabaribao/work/papers/downscaling/main/results/tests/unet/unet_exp1_v2_bg_bs1024_lr1e-4/region_lat_21.0_37.0_lon_-18.0_0.0/train_1979_01_01_2005_12_31/test_2006_01_01_2020_12_31/gridbox_0.0001_bernoulli_gamma_150ep_lr_sched_wd_gc_dropout_gn/output_data/unet_v2_predictions_era5_to_mswep.nc
  variable_name: precipitation
- name: bs1024_lr1e-5
  file_path: /srv/data/mohammad.elaabaribao/work/papers/downscaling/main/results/tests/unet/unet_exp1_v2_bg_bs1024_lr1e-5/region_lat_21.0_37.0_lon_-18.0_0.0/train_1979_01_01_2005_12_31/test_2006_01_01_2020_12_31/gridbox_1e-05_bernoulli_gamma_150ep_lr_sched_wd_gc_dropout_gn/output_data/unet_v2_predictions_era5_to_mswep.nc
  variable_name: precipitation
postproc:
  mean:
    enable: true
    bias: true
    rmse: true
    correlation: true
  extreme:
    enable: true
    cdd: true
    qqplot: true
    r01: false
    r99: false
    r95: true
    r99_freq: false
    r95_freq: true
    rocss: false
custom_limits:
  bias:
    spatial:
    - -2
    - -1.5
    - -1
    - -0.5
    - -0.2
    - 0
    - 0.2
    - 0.5
    - 1
    - 1.5
    - 2
    boxplot:
    - -1
    - 1
    temporal:
    - -1
    - 1
  rmse:
    spatial:
    - 0
    - 0.2
    - 0.4
    - 0.6
    - 0.8
    - 1.0
    - 1.5
    - 2.0
    boxplot:
    - 0
    - 1
    temporal:
    - 0
    - 1
  mean:
    spatial:
    - 0
    - 0.1
    - 0.3
    - 0.5
    - 1
    - 2
    - 3
    - 4
    - 5
    boxplot:
    - 0
    - 6
    temporal:
    - 0
    - 0.1
    - 0.3
    - 0.5
    - 1
    - 2
    - 3
    - 4
    - 5
  cdd:
    spatial:
    - 0
    - 50
    - 100
    - 150
    - 200
    - 250
    - 300
    - 350
    boxplot:
    - 100
    - 250
    temporal:
    - 100
    - 200
  r01:
    spatial:
    - 0
    - 10
    - 20
    - 30
    - 40
    - 50
    - 60
    - 70
    - 80
    boxplot:
    - 0
    - 80
    temporal:
    - 0
    - 80
  r95:
    spatial:
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 15
    boxplot:
    - 0
    - 15
    temporal:
    - 0
    - 15
  r99:
    spatial:
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 15
    boxplot:
    - 0
    - 15
    temporal:
    - 0
    - 15
  r95_freq:
    spatial:
    - 0
    - 1
    - 2
    - 3
    - 5
    - 7
    - 10
    boxplot:
    - 0
    - 3
    temporal:
    - 0
    - 3
  r99_freq:
    spatial:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    boxplot:
    - 0
    - 6
    temporal:
    - 0
    - 6
  qqplot:
    spatial:
    - 0
    - 20
    - 40
    - 60
    - 80
    boxplot:
    - 0
    - 80
    temporal:
    - 0
    - 80
  correlation:
    spatial:
    - -1
    - -0.8
    - -0.6
    - -0.4
    - -0.2
    - 0
    - 0.2
    - 0.4
    - 0.6
    - 0.8
    - 1
    boxplot:
    - -1
    - 1
    temporal:
    - -1
    - 1
  rocss:
    spatial:
    - 0
    - 0.2
    - 0.4
    - 0.6
    - 0.8
    - 1
    boxplot:
    - 0
    - 1
    temporal:
    - 0
    - 1
