# Author: M. El Aabaribaoune (@um6p)
experiment: "inference_lmdz35_to_mswep"
parameters:
 start_date: "1979-01-01"
 end_date: "2014-12-31"
 region: "allmorr"
 regions:
 - "allmorr"
 mask_land: true
 only_morocco: true
 predictand: "pr"
 plot_only: false
 impose_robust_limits: true
 show_title_metadata: true
 customize_colorbars: true
 plot_periods:
 - Annual
 - DJF
 - MAM
 - JJA
 - SON

reference:
 name: mswep
 file_path: /home/mohammad.elaabaribao/lustre/climat-um6p-st-iwri-7ksifkvwkuy/users/mohammad.elaabaribao/data//era5ztquv/1979_2020/all_data/mswep_1979_2020.nc
 variable_name: precipitation

datasets:
- name: LMDZ35
 file_path: datasets/raw_lmdz35_10km.nc
 variable_name: precipitation
- name: GLM
 file_path: ../inference/results/1979_2014/glm_precip_l2/glm_lmdz_35_present_true.nc
 variable_name: precipitation
- name: CNN
 file_path: ../inference/results/1979_2014/cnn_exp5/cnn_lmdz_35_present_true.nc
 variable_name: precipitation
- name: UNET
 file_path: ../inference/results/1979_2014/cnn_exp3/cnn_lmdz_35_present_true.nc
 variable_name: precipitation
- name: ViT
 file_path: ../inference/results/1979_2014/vit_precip_exp21_best_hybrid/vit_lmdz_250_present_true.nc
 variable_name: precipitation

postproc:
 mean:
 enable: true
 bias: true
 rmse: true
 correlation: true
 extreme:
 enable: true
 cdd: true
 cdd_thresholds: [1.0, 0.5]
 qqplot: false
 r01: false
 r99: false
 r95: true
 r99_freq: false
 r95_freq: true
 rocss: false

visualisation:
 model_colors:
 MSWEP: "#000000"
 LMDZ35: "#E76F51"
 GLM: "#2A9D8F"
 CNN: "#457B9D"
 U-Net: "#1D3557"
 UNET: "#1D3557"
 ViT: "#E63946"
 VIT: "#E63946"
 metrics:
 mean:
 colormaps:
 spatial: "custom_precip"
 difference: "custom_bias"
 limits:
 spatial: [0, 0.1, 0.3, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5]
 boxplot: [0, 6]
 temporal: [0, 0.1, 0.3, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5, 5.5, 6]
 bias:
 colormaps:
 spatial: "custom_bias"
 difference: "custom_bias"
 limits:
 spatial: [-5, -4, -3, -2, -1, -0.5, -0.2, -0.1, 0, 0.1, 0.2, 0.5, 1, 2, 3, 4, 5]
 boxplot: [-2.5, 2.5]
 temporal: [-2.5, 2.5]
 rmse:
 colormaps:
 spatial: "custom_precip"
 difference: "custom_bias"
 limits:
 spatial: [0, 0.1, 0.3, 0.5, 1, 1.5, 2]
 boxplot: [0, 2]
 temporal: [0, 2]
 cdd:
 colormaps:
 spatial: "YlOrBr"
 difference: "custom_bias"
 limits:
 spatial: [0, 10, 20, 30, 40, 60, 80, 100, 150, 200, 250, 300, 400]
 difference: [-100, -80, -60, -40, -20, 0, 20, 40, 60, 80, 100]
 boxplot: [0, 400]
 temporal: [0, 400]
 r95:
 colormaps:
 spatial: "custom_precip"
 difference: "custom_bias"
 limits:
 spatial: [0, 0.1, 0.3, 0.5, 1, 1.5, 2, 2.5, 3, 4, 5, 6, 7, 8, 9, 10]
 difference: [-5, -4, -3, -2, -1, -0.5, -0.2, -0.1, 0, 0.1, 0.2, 0.5, 1, 2, 3, 4, 5]
 boxplot: [0, 10]
 temporal: [0, 0.1, 0.3, 0.5, 1, 1.5, 2, 2.5, 3, 4, 5, 6, 7, 8, 9, 10]
 r95_freq:
 colormaps:
 spatial: "custom_freq"
 difference: "custom_bias"
 limits:
 spatial: [0, 2, 4, 6, 8, 10, 15]
 difference: [-10, -8, -6, -4, -2, -1, 0, 1, 2, 4, 6, 8, 10]
 boxplot: [0, 15]
 temporal: [0, 15]
 correlation:
 colormaps:
 spatial: "RdBu_r"
 difference: "custom_bias"
 limits:
 spatial: [-1, -0.8, -0.6, -0.4, -0.2, 0, 0.2, 0.4, 0.6, 0.8, 1]
 boxplot: [-1, 1]
 temporal: [-1, 1]
 default:
 colormaps:
 spatial: "viridis"
 difference: "custom_bias"
